Do not register a task definition unless container def json is supplied

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -54,124 +54,125 @@ fi
 
 if [ -n "${BUILDKITE_PLUGIN_ECS_DEPLOY_CONTAINER_DEFINITIONS:-}" ]; then
   container_definitions="${BUILDKITE_PLUGIN_ECS_DEPLOY_CONTAINER_DEFINITIONS}"
-else
-  container_definitions=$(mktemp)
-  trap 'rm "${container_definitions}"' EXIT
-  jq '.containerDefinitions' "${task_file}" >"${container_definitions}"
-fi
 
-if [ "$(jq -r '. | type' "${container_definitions}")" != "array" ]; then
-  echo 'Invalid container definition (should be in the format of [{"image": "..."}] )'
-  exit 1
-fi
-
-# necessary for compatibility with bash 4.3
-if plugin_read_list_into_result "ENV"; then
-  env_vars=("${result[@]}")
-else
-  env_vars=()
-fi
-
-# jq has no in-place edition https://github.com/jqlang/jq/issues/105
-container_definitions_json=$(cat "${container_definitions}")
-image_idx=0
-for image in "${images[@]}"; do
-  container_definitions_json=$(
-    echo "$container_definitions_json" \
-    | jq --arg IMAGE "$image" ".[${image_idx}].image=\$IMAGE"
-  )
-
-  # this check is only necessary to be compatible with bash 4.3 (see issue #81)
-  if [ "${#env_vars[@]}" -gt 0 ]; then
-    for env_var in "${env_vars[@]}"; do
-      IFS="=" read -r -a var_val <<< "${env_var}"
-      container_definitions_json=$(
-        echo "$container_definitions_json" \
-        | jq --arg ENVVAR "${var_val[0]}" --arg ENVVAL "${var_val[1]}" \
-          ".[${image_idx}].environment += [{\"name\": \$ENVVAR, \"value\": \$ENVVAL}]"
-      )
-    done
+  if [ "$(jq -r '. | type' "${container_definitions}")" != "array" ]; then
+    echo 'Invalid container definition (should be in the format of [{"image": "..."}] )'
+    exit 1
   fi
 
-  image_idx=$((image_idx+1))
-done
+  # necessary for compatibility with bash 4.3
+  if plugin_read_list_into_result "ENV"; then
+    env_vars=("${result[@]}")
+  else
+    env_vars=()
+  fi
 
-echo "--- :ecs: Registering new task definition for ${task_family}"
-register_command=(aws ecs register-task-definition
-  ${aws_default_args[@]+"${aws_default_args[@]}"}
-  --family "${task_family}"
-  --container-definitions "${container_definitions_json}"
-)
+  # jq has no in-place edition https://github.com/jqlang/jq/issues/105
+  container_definitions_json=$(cat "${container_definitions}")
+  image_idx=0
+  for image in "${images[@]}"; do
+    container_definitions_json=$(
+      echo "$container_definitions_json" |
+        jq --arg IMAGE "$image" ".[${image_idx}].image=\$IMAGE"
+    )
 
-execution_role=${BUILDKITE_PLUGIN_ECS_DEPLOY_EXECUTION_ROLE:-$(jq -r '.executionRoleArn // ""' "${task_file}")}
-if [ -n "${execution_role}" ]; then
-  register_command+=(--execution-role-arn "${execution_role}")
+    # this check is only necessary to be compatible with bash 4.3 (see issue #81)
+    if [ "${#env_vars[@]}" -gt 0 ]; then
+      for env_var in "${env_vars[@]}"; do
+        IFS="=" read -r -a var_val <<<"${env_var}"
+        container_definitions_json=$(
+          echo "$container_definitions_json" |
+            jq --arg ENVVAR "${var_val[0]}" --arg ENVVAL "${var_val[1]}" \
+              ".[${image_idx}].environment += [{\"name\": \$ENVVAR, \"value\": \$ENVVAL}]"
+        )
+      done
+    fi
+
+    image_idx=$((image_idx + 1))
+  done
+
+  echo "--- :ecs: Registering new task definition for ${task_family}"
+  register_command=(aws ecs register-task-definition
+    ${aws_default_args[@]+"${aws_default_args[@]}"}
+    --family "${task_family}"
+    --container-definitions "${container_definitions_json}"
+  )
+
+  execution_role=${BUILDKITE_PLUGIN_ECS_DEPLOY_EXECUTION_ROLE:-$(jq -r '.executionRoleArn // ""' "${task_file}")}
+  if [ -n "${execution_role}" ]; then
+    register_command+=(--execution-role-arn "${execution_role}")
+  fi
+
+  task_cpu=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_CPU:-$(jq -r '.cpu // ""' "${task_file}")}
+  if [ -n "${task_cpu}" ]; then
+    register_command+=(--cpu "${task_cpu}")
+  fi
+
+  task_ephemeral=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_EPHEMERAL_STORAGE:-$(jq -r '.ephemeralStorage.sizeInGiB // ""' "${task_file}")}
+  if [ -n "${task_ephemeral}" ]; then
+    register_command+=(--ephemeral-storage "sizeInGiB=${task_ephemeral}")
+  fi
+
+  task_ipc=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_IPC_MODE:-$(jq -r '.ipcMode // ""' "${task_file}")}
+  if [ -n "${task_ipc}" ]; then
+    register_command+=(--ipc-mode "${task_ipc}")
+  fi
+
+  task_memory=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_MEMORY:-$(jq -r '.memory // ""' "${task_file}")}
+  if [ -n "${task_memory}" ]; then
+    register_command+=(--memory "${task_memory}")
+  fi
+
+  task_network=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_NETWORK_MODE:-$(jq -r '.networkMode // ""' "${task_file}")}
+  if [ -n "${task_network}" ]; then
+    register_command+=(--network-mode "${task_network}")
+  fi
+
+  task_pid=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_PID_MODE:-$(jq -r '.pidMode // ""' "${task_file}")}
+  if [ -n "${task_pid}" ]; then
+    register_command+=(--pid-mode "${task_pid}")
+  fi
+
+  task_role_arn=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_ROLE_ARN:-$(jq -r '.taskRoleArn // ""' "${task_file}")}
+  if [ -n "${task_role_arn}" ]; then
+    register_command+=(--task-role-arn "${task_role_arn}")
+  fi
+
+  # Following options are to keep values (they are complex for plugin-based configurations)
+  task_volumes=$(jq -r '.volumes // ""' "${task_file}")
+  if [ -n "${task_volumes}" ]; then
+    register_command+=(--volumes "${task_volumes}")
+  fi
+
+  task_placement=$(jq -r '.placementConstraints // ""' "${task_file}")
+  if [ -n "${task_placement}" ]; then
+    register_command+=(--placement-constraints "${task_placement}")
+  fi
+
+  task_compat_reqs=$(jq -r '.requiresCompatibilities // ""' "${task_file}")
+  if [ -n "${task_compat_reqs}" ]; then
+    register_command+=(--requires-compatibilities "${task_compat_reqs}")
+  fi
+
+  echo "--- :ecs: register command:"
+
+  json_output=$("${register_command[@]}")
+  register_exit_code=$?
+
+  if [[ $register_exit_code -ne 0 ]]; then
+    echo "+++ ^^^"
+    echo "+++ Failed to register task defintion"
+    exit "$register_exit_code"
+  fi
+
+  task_revision=$(jq '.taskDefinition.revision' <<<"$json_output")
+  echo "Registered ${task_family}:${task_revision}"
+
+else
+  # No container definition was supplied, so we use the most recent rev
+  task_revision=$(jq '.revision' "${task_file}")
+  echo "--- :ecs: Using existing task definition v${task_revision}"
 fi
-
-task_cpu=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_CPU:-$(jq -r '.cpu // ""' "${task_file}")}
-if [ -n "${task_cpu}" ]; then
-  register_command+=(--cpu "${task_cpu}")
-fi
-
-task_ephemeral=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_EPHEMERAL_STORAGE:-$(jq -r '.ephemeralStorage.sizeInGiB // ""' "${task_file}")}
-if [ -n "${task_ephemeral}" ]; then
-  register_command+=(--ephemeral-storage "sizeInGiB=${task_ephemeral}")
-fi
-
-task_ipc=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_IPC_MODE:-$(jq -r '.ipcMode // ""' "${task_file}")}
-if [ -n "${task_ipc}" ]; then
-  register_command+=(--ipc-mode "${task_ipc}")
-fi
-
-task_memory=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_MEMORY:-$(jq -r '.memory // ""' "${task_file}")}
-if [ -n "${task_memory}" ]; then
-  register_command+=(--memory "${task_memory}")
-fi
-
-task_network=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_NETWORK_MODE:-$(jq -r '.networkMode // ""' "${task_file}")}
-if [ -n "${task_network}" ]; then
-  register_command+=(--network-mode "${task_network}")
-fi
-
-task_pid=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_PID_MODE:-$(jq -r '.pidMode // ""' "${task_file}")}
-if [ -n "${task_pid}" ]; then
-  register_command+=(--pid-mode "${task_pid}")
-fi
-
-task_role_arn=${BUILDKITE_PLUGIN_ECS_DEPLOY_TASK_ROLE_ARN:-$(jq -r '.taskRoleArn // ""' "${task_file}")}
-if [ -n "${task_role_arn}" ]; then
-  register_command+=(--task-role-arn "${task_role_arn}")
-fi
-
-# Following options are to keep values (they are complex for plugin-based configurations)
-task_volumes=$(jq -r '.volumes // ""' "${task_file}")
-if [ -n "${task_volumes}" ]; then
-  register_command+=(--volumes "${task_volumes}")
-fi
-
-task_placement=$(jq -r '.placementConstraints // ""' "${task_file}")
-if [ -n "${task_placement}" ]; then
-  register_command+=(--placement-constraints "${task_placement}")
-fi
-
-task_compat_reqs=$(jq -r '.requiresCompatibilities // ""' "${task_file}")
-if [ -n "${task_compat_reqs}" ]; then
-  register_command+=(--requires-compatibilities "${task_compat_reqs}")
-fi
-
-echo "--- :ecs: register command:"
-
-json_output=$("${register_command[@]}")
-register_exit_code=$?
-
-if [[ $register_exit_code -ne 0 ]] ; then
-  echo "+++ ^^^"
-  echo "+++ Failed to register task defintion"
-  exit "$register_exit_code"
-fi
-
-task_revision=$(jq '.taskDefinition.revision' <<< "$json_output")
-echo "Registered ${task_family}:${task_revision}"
 
 # Take advantage of the fact that ISO8601 format is sortable
 update_time=$(date +'%Y-%m-%dT%H:%M:%S')
